wasps = [
    {type: "Queen", health: 80},   
    {type: "worker", health: 68},   
    {type: "worker", health: 68},   
    {type: "worker", health: 68},   
    {type: "worker", health: 68},   
    {type: "worker", health: 68},   
    {type: "drone", health: 60},   
    {type: "drone", health: 60},   
    {type: "drone", health: 60},   
    {type: "drone", health: 60},   
    {type: "drone", health: 60},   
    {type: "drone", health: 60},   
    {type: "drone", health: 60},   
    {type: "drone", health: 60},   
]